Add logging to GitHub action

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -55,3 +55,6 @@ jobs:
           echo "Logs from failed permissioned tokens container:"
           docker ps -a
           docker logs $(docker ps -a -q --filter name=alphabill-permissioned-tokens || true) || true
+          echo "Logs from failed upload configuration container:"
+          docker ps -a
+          docker logs $(docker ps -a -q --filter name=upload-configurations || true) || true    
